import type {
  ChampionsData,
  Home,
  MatchDetail,
  MatchRecords,
  PhaseDetail,
  PlayerComparison,
  PlayerLeaderboard,
  PlayerList,
  PlayerMatches,
  PlayerMilestones,
  PlayerOpponents,
  PlayerProfile,
  PlayerSeasons,
  SearchResults,
  SeasonDetail,
  SeasonListItem,
  SeasonTopScorers,
  SingleRecords,
  SiteMeta,
  TeamComparison,
  TeamLeaderboard,
  TeamLeaders,
  TeamList,
  TeamMatches,
  TeamOpponents,
  TeamProfile,
  TeamSeasons,
  TeamSquad,
  TournamentDetail,
  TournamentListItem,
} from '@ligapedia/contracts';
import { queryOptions } from '@tanstack/react-query';
import { apiGet, type Params } from './api';

/** One query-options factory per endpoint; keys are [path, params]. */
const q = <T>(path: string, params: Params = {}) =>
  queryOptions({
    queryKey: [path, params] as const,
    queryFn: ({ signal }) => apiGet<T>(path, params, signal),
  });

export const queries = {
  meta: () => q<SiteMeta>('meta'),
  home: () => q<Home>('inicio'),
  seasons: () => q<SeasonListItem[]>('temporadas'),
  season: (year: number) => q<SeasonDetail>(`temporadas/${year}`),
  tournaments: (p: Params) => q<TournamentListItem[]>('torneos', p),
  tournament: (id: number) => q<TournamentDetail>(`torneos/${id}`),
  phase: (id: number, p: Params) => q<PhaseDetail>(`fases/${id}`, p),
  champions: (p: Params) => q<ChampionsData>('campeones', p),
  match: (id: number) => q<MatchDetail>(`partidos/${id}`),
  players: (p: Params) => q<PlayerList>('jugadores', p),
  player: (id: number) => q<PlayerProfile>(`jugadores/${id}`),
  playerSeasons: (id: number) => q<PlayerSeasons>(`jugadores/${id}/temporadas`),
  playerMatches: (id: number, p: Params) => q<PlayerMatches>(`jugadores/${id}/partidos`, p),
  playerMilestones: (id: number) => q<PlayerMilestones>(`jugadores/${id}/hitos`),
  playerOpponents: (id: number, p: Params) => q<PlayerOpponents>(`jugadores/${id}/rivales`, p),
  teams: (p: Params) => q<TeamList>('equipos', p),
  team: (id: number) => q<TeamProfile>(`equipos/${id}`),
  teamSeasons: (id: number) => q<TeamSeasons>(`equipos/${id}/temporadas`),
  teamSquad: (id: number, p: Params) => q<TeamSquad>(`equipos/${id}/plantel`, p),
  teamLeaders: (id: number) => q<TeamLeaders>(`equipos/${id}/lideres`),
  teamOpponents: (id: number, p: Params) => q<TeamOpponents>(`equipos/${id}/rivales`, p),
  teamMatches: (id: number, p: Params) => q<TeamMatches>(`equipos/${id}/partidos`, p),
  compareTeams: (p: Params) => q<TeamComparison>('comparar/equipos', p),
  comparePlayers: (p: Params) => q<PlayerComparison>('comparar/jugadores', p),
  playerRecords: (metric: string, p: Params) => q<PlayerLeaderboard>(`records/jugadores/${metric}`, p),
  teamRecords: (metric: string, p: Params) => q<TeamLeaderboard>(`records/equipos/${metric}`, p),
  matchRecords: (type: string, p: Params) => q<MatchRecords>(`records/partidos/${type}`, p),
  singleRecords: (p: Params) => q<SingleRecords>('records/hitos', p),
  seasonTopScorers: (p: Params) => q<SeasonTopScorers>('records/goleadores-por-temporada', p),
  search: (text: string) => q<SearchResults>('buscar', { q: text }),
};
